CREATE TABLE `cliente` (
  `clienteId` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `organizacionId` smallint(5) unsigned NOT NULL,
  `tipoClienteId` smallint(5) unsigned NOT NULL,
  `tipoIdentificacionId` smallint(5) unsigned NOT NULL,
  `tipoNITId` smallint(5) unsigned DEFAULT NULL,
  `nit` varchar(20) DEFAULT NULL,
  `cui` varchar(20) DEFAULT NULL,
  `idExtranjero` varchar(20) DEFAULT NULL,
  `razonSocial` varchar(260) NOT NULL,
  `nombres` varchar(130) DEFAULT NULL,
  `apellidos` varchar(130) DEFAULT NULL,
  `nombre` varchar(260) NOT NULL,
  `correo` varchar(255) DEFAULT NULL,
  `fechaNacimiento` date DEFAULT NULL,
  `celular` varchar(20) DEFAULT NULL,
  `telefono` varchar(20) DEFAULT NULL,
  `fechaCreacion` datetime NOT NULL,
  `fechaActualizacion` datetime NOT NULL,
  `fotografia` varchar(2000) DEFAULT NULL,
  `extension` varchar(10) DEFAULT NULL,
  `clienteExternoId` bigint(20) unsigned DEFAULT NULL,
  `categoriaClienteId` int(10) unsigned DEFAULT NULL,
  `noContador` varchar(200) DEFAULT NULL,
  `historialUnificacion` longtext DEFAULT NULL CHECK (json_valid(`historialUnificacion`)),
  `telefonoCodPais` varchar(5) DEFAULT NULL,
  `celularCodPais` varchar(5) DEFAULT NULL,
  `nacionalidadId` smallint(5) unsigned DEFAULT NULL,
  `profesion` varchar(100) DEFAULT NULL,
  `estadoCivilId` smallint(5) unsigned DEFAULT NULL,
  `migrados` smallint(6) DEFAULT 0,
  `telefonoExtension` varchar(10) DEFAULT NULL,
  `nitRepresentanteLegal` varchar(20) DEFAULT NULL,
  `generoId` smallint(5) unsigned DEFAULT NULL,
  `permiteCuentaCorrienteId` smallint(5) unsigned NOT NULL DEFAULT 2,
  `aplicaMaximoCreditoCCId` smallint(5) unsigned DEFAULT NULL,
  `maximoCreditoCC` decimal(24,2) DEFAULT NULL,
  `maximoDiasCreditoCC` smallint(5) unsigned DEFAULT NULL,
  `esSistema` smallint(5) unsigned DEFAULT 2,
  `razonComercial` varchar(500) DEFAULT NULL,
  `ventaIncluyeIVA` smallint(5) unsigned DEFAULT 1,
  PRIMARY KEY (`clienteId`,`organizacionId`),
  UNIQUE KEY `idExtranjero` (`idExtranjero`,`organizacionId`),
  UNIQUE KEY `nit` (`nit`,`organizacionId`),
  UNIQUE KEY `cui_nit_organizacionId` (`cui`,`nit`,`organizacionId`),
  KEY `organizacionId` (`organizacionId`),
  KEY `tipoClienteId` (`tipoClienteId`),
  KEY `tipoIdentificacionId` (`tipoIdentificacionId`),
  KEY `tipoNITId` (`tipoNITId`),
  KEY `categoriaClienteId` (`categoriaClienteId`,`organizacionId`),
  KEY `estadoCivilId` (`estadoCivilId`,`organizacionId`),
  KEY `nacionalidadId` (`nacionalidadId`,`organizacionId`),
  KEY `idx_cli_orgTipo` (`tipoClienteId`,`organizacionId`),
  KEY `generoId` (`generoId`,`organizacionId`),
  KEY `permiteCuentaCorrienteId` (`permiteCuentaCorrienteId`),
  KEY `aplicaMaximoCreditoCCId` (`aplicaMaximoCreditoCCId`),
  KEY `esSistema` (`esSistema`),
  KEY `idx_cliente_nit` (`nit`),
  KEY `idx_cliente_cui` (`cui`),
  KEY `ventaIncluyeIVA` (`ventaIncluyeIVA`),
  CONSTRAINT `cliente_ibfk_1` FOREIGN KEY (`organizacionId`) REFERENCES `organizacion` (`organizacionId`),
  CONSTRAINT `cliente_ibfk_10` FOREIGN KEY (`permiteCuentaCorrienteId`) REFERENCES `estado` (`estadoId`),
  CONSTRAINT `cliente_ibfk_11` FOREIGN KEY (`aplicaMaximoCreditoCCId`) REFERENCES `estado` (`estadoId`),
  CONSTRAINT `cliente_ibfk_12` FOREIGN KEY (`esSistema`) REFERENCES `estado` (`estadoId`),
  CONSTRAINT `cliente_ibfk_13` FOREIGN KEY (`ventaIncluyeIVA`) REFERENCES `estado` (`estadoId`),
  CONSTRAINT `cliente_ibfk_2` FOREIGN KEY (`tipoClienteId`) REFERENCES `tipoCliente` (`tipoClienteId`),
  CONSTRAINT `cliente_ibfk_3` FOREIGN KEY (`tipoIdentificacionId`) REFERENCES `tipoIdentificacion` (`tipoIdentificacionId`),
  CONSTRAINT `cliente_ibfk_4` FOREIGN KEY (`tipoNITId`) REFERENCES `tipoNIT` (`tipoNITId`),
  CONSTRAINT `cliente_ibfk_5` FOREIGN KEY (`categoriaClienteId`, `organizacionId`) REFERENCES `categoriaCliente` (`categoriaClienteId`, `organizacionId`),
  CONSTRAINT `cliente_ibfk_6` FOREIGN KEY (`nacionalidadId`, `organizacionId`) REFERENCES `nacionalidad` (`nacionalidadId`, `organizacionId`),
  CONSTRAINT `cliente_ibfk_7` FOREIGN KEY (`estadoCivilId`, `organizacionId`) REFERENCES `estadoCivil` (`estadoCivilId`, `organizacionId`),
  CONSTRAINT `cliente_ibfk_8` FOREIGN KEY (`nacionalidadId`, `organizacionId`) REFERENCES `nacionalidad` (`nacionalidadId`, `organizacionId`),
  CONSTRAINT `cliente_ibfk_9` FOREIGN KEY (`generoId`, `organizacionId`) REFERENCES `genero` (`generoId`, `organizacionId`)
) ENGINE=InnoDB AUTO_INCREMENT=90163 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci